// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqNxgfit9MAHwsB1dk9TIp_OLG72XeAE',
    appId: '1:220275559574:web:dd58d641a3f383108f46b7',
    messagingSenderId: '220275559574',
    projectId: 'smart-travel-planner-1b556',
    authDomain: 'smart-travel-planner-1b556.firebaseapp.com',
    storageBucket: 'smart-travel-planner-1b556.firebasestorage.app',
    measurementId: 'G-1D366T5J6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcY7H-WQq7d7XyzzvGMQ8CzTsQPglJntM',
    appId: '1:220275559574:android:71b74424b1bf40be8f46b7',
    messagingSenderId: '220275559574',
    projectId: 'smart-travel-planner-1b556',
    storageBucket: 'smart-travel-planner-1b556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDLDXB3T_Bo_1r1eRS8CrsFMq9hIKOL8',
    appId: '1:220275559574:ios:33826312a48734ac8f46b7',
    messagingSenderId: '220275559574',
    projectId: 'smart-travel-planner-1b556',
    storageBucket: 'smart-travel-planner-1b556.firebasestorage.app',
    iosBundleId: 'com.example.smartTravellerPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFqNxgfit9MAHwsB1dk9TIp_OLG72XeAE',
    appId: '1:220275559574:web:f51d1ae07a425cad8f46b7',
    messagingSenderId: '220275559574',
    projectId: 'smart-travel-planner-1b556',
    authDomain: 'smart-travel-planner-1b556.firebaseapp.com',
    storageBucket: 'smart-travel-planner-1b556.firebasestorage.app',
    measurementId: 'G-T7VKB7J9MV',
  );
}
